---
- name: create vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vm_folder }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        state: "{{ vm_state }}"
        guest_id: "{{ vm_guestid }}"
        esxi_hostname: "{{ esxi_hostname }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: "{{ vm_hw_scsi }}"
        networks:
          - name: "{{ vm_net_name }}"
            mac: "{{ vm_net_mac }}"
            ip: "{{ vm_net_ip }}"
            netmask: "{{ vm_net_netmask }}"
            device_type: "{{ vm_net_type }}"
      register: deploy_vm
