---
- name: delete vm from inventory
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Delete vm from inventory
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        state: absent

