---
- name: vm disk remove
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: remove disk from vm
      vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        disk:
          - state: absent
            destroy: false
            scsi_controller: "{{ vm_disk_scsi_controller }}"
            unit_number: "{{ vm_disk_scsi_unit }}"
