---
- name: start vm
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: power on
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
        validate_certs: false
        state: powered-on
